version: '3.8'
services:
  qr-generator:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm start
